### PR TITLE
Changes from my version

### PR DESCRIPTION
**Pull request by thesupersonic16**
Please don't mind the messy code, I have tried to clean it a little,  just never expected the source to be released when i was writing it.

### CODE REVIEW

**Comment by thesupersonic16** [comment]
Just Wait, Gotta look into the error on Appveyor.

**Comment by thesupersonic16** [comment]
Never mind, Seems you have not set it up to build correctly.

**Comment by Xeeynamo** [comment]
Your code is good, do not worry! I just adjusted some names and added frames duplication on RSDK3 too.

One idea that I had looking your changes is that every RSDK object should implement System.ICloneable, so it is possible to clone/duplicate in a transparent way without checking the object's type (eg. _frame is RSDK5.Frame_).

Your discovery about frames duration is great! I was able to complete the rendering system for those frames with speed = 1 or 2. Have you an idea of what ID is? I imagine something about game's scripts. In what animation's file the ID is different than 0?

**Comment by thesupersonic16** [comment]
I didn't discover the duration nor did I for ID(B0M did), I Just wanted to add as much useful and requested features.
Tho, I did do the programming while i did none of the discovery since later on you written a better version then mine.
The main reason I started writing my version was because at the time yours could only export to RSDK3 not 5 and people wanted to export it to Mania, Which i did, But later on you made it export to 5, I also have written stuff for Textures, and ofc you also written a better one afterwards. Sorry if i made alot of mistakes, I usually program in Winforms with fields. :)

I must be no where near writing good C# code, at least I'm learning. Thanks for merging. :)

**Comment by Xeeynamo** [comment]
You made no mistakes but improvements. Collaboration is the key!

PS. WPF > WinForms.

**Pull request merged**
